name: tradetrove
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.18.0
  firebase_core: ^2.31.1
  firebase_database: ^10.4.11
  firebase_storage: ^11.7.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_signin_button: ^2.0.0
  geolocator: ^12.0.0
  google_nav_bar: ^5.0.6
  image_picker: ^1.1.1
  path: ^1.9.0
  google_maps_flutter: ^2.6.1
  flutter_map: ^6.1.0
  url_launcher: ^6.2.6
  latlong2: ^0.9.1
  flutter_config: ^2.0.2

flutter_launch_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoTt.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/logoTt.png
  - assets/images/shopping-items.png
  - assets/images/jarakTempuh.png
  - assets/images/bahanBakar.png
  - assets/images/lokasi.png
  - assets/images/chatIcon.png

  fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Anton-Regular.ttf
      - asset: assets/fonts/Lato-Bold.ttf
        weight: 700
